# Generated by Django 4.2.4 on 2023-08-17 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secretory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="secratory",
            name="sec_from",
            field=models.DateField(default=datetime.date(2023, 8, 17)),
        ),
    ]
