# Generated by Django 4.2.4 on 2023-08-17 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secretory", "0002_secratory_sec_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secratory",
            name="sec_from",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 17, 2, 47, 47, 646942, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
