# Generated by Django 4.2.4 on 2023-08-24 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secretory", "0004_secratory_profile_pic_alter_secratory_sec_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secratory",
            name="sec_from",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 24, 2, 54, 9, 909400, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
