# Generated by Django 4.2.4 on 2023-08-24 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secretory", "0005_alter_secratory_sec_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secratory",
            name="sec_from",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 24, 3, 0, 53, 428775, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
