# Generated by Django 4.2.4 on 2023-08-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Secretory", "0007_alter_secratory_sec_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secratory",
            name="sec_from",
            field=models.DateField(auto_now_add=True),
        ),
    ]
