# Generated by Django 4.2.4 on 2023-09-02 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0004_member_password"),
        ("Secretory", "0009_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=50)),
                ("des", models.TextField()),
                (
                    "pic",
                    models.FileField(blank=True, null=True, upload_to="complains/"),
                ),
                ("complain_on", models.DateTimeField(auto_now_add=True)),
                ("solve_on", models.DateTimeField(blank=True, null=True)),
                ("solve", models.BooleanField(default=False)),
                (
                    "complain_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Members.member"
                    ),
                ),
                (
                    "solve_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Secretory.secratory",
                    ),
                ),
            ],
        ),
    ]
