# Generated by Django 4.2.4 on 2023-09-05 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0004_member_password"),
        ("Secretory", "0011_alter_complain_solve_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("des", models.TextField()),
                ("notice_on", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
                ("read_time", models.DateTimeField(blank=True, null=True)),
                (
                    "send_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Secretory.secratory",
                    ),
                ),
                (
                    "send_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Members.member"
                    ),
                ),
            ],
        ),
    ]
