# Generated by Django 4.2.4 on 2023-08-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0002_alter_member_res_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="pic",
            field=models.FileField(default="avtar.png", upload_to="member_pic"),
        ),
    ]
