# Generated by Django 4.2.4 on 2023-08-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0003_member_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
