# Generated by Django 4.2.4 on 2023-09-12 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Members", "0004_member_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Main",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pay_on", models.DateTimeField(auto_now_add=True)),
                ("verify", models.BooleanField(default=False)),
                ("amount", models.IntegerField()),
                ("trans_id", models.CharField(max_length=30)),
                ("pay_for", models.DateField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Members.member"
                    ),
                ),
            ],
        ),
    ]
